### ISSUE TITLE
Layout issues after Text Copy changes (Primary and Partner DAO Stages)

### ISSUE THREAD

**Issue by hiaux0** [PrimeDAO/prime-deals-dapp#219]
Probably needs Jaap's input

![image](https://user-images.githubusercontent.com/30693990/155586268-a69bc3d3-0bd1-40ce-b9af-1e3f800da52d.png)

**Comment by BartuCulha** [comment]
Hey @hiaux0 what's the issue? My guess is that the indentation caused by bullet points is a bit off.

I have communicated this with the design team, here's what we can do:
-Indentation looks ok 
-We could change the color of the bullet points to maybe make it look a bit better
- Maybe we can reduce the space between each paragraph

**Comment by curvelabs-dev** [comment]
This is all "maybes", so sounds all optional and like the status quo is ok.  Is there anything here that is required?  If required, can we please have a spec on the colors for the bullets?  @BartuCulha  @blink-km
