### ISSUE TITLE
If social Links are optional, they should not be treated as required

### ISSUE THREAD

**Issue by dkent600** [PrimeDAO/prime-deals-dapp#286]
Happens on both DAO pages:

![image](https://user-images.githubusercontent.com/1821666/157131883-4606a5d2-0b94-4ffc-8379-0db054c90af2.png)

**Comment by BartuCulha** [comment]
They are still treated as required.

![Create-an-Open-Proposal-Prime-Deals (13)](https://user-images.githubusercontent.com/24368665/157858280-0dcd986d-7b44-4097-a774-ddb2203662b4.png)

**Comment by IonelLupu** [comment]
Hi @BartuCulha 

I assume you intentionally added a new social link record by clicking the "Add social media" button. If so, the user is required to add valid social links. Social links are not required if there are none added. Clicking the "Add social media" button creates a new empty record in the Deal's data but the data inside it MUST be valid in order to proceed to the next step. You cannot have an invalid social media record. That's why you get the error messages.

To not be required to fill in the social media links inputs, just use the "trash" icon to delete it.

**Comment by IonelLupu** [comment]
@BartuCulha  should we close this issue? (or move it into another status)

**Comment by BartuCulha** [comment]
Closing it!
