### ISSUE TITLE
deal type should be on a separate line

### ISSUE THREAD

**Issue by renc-curvelabs** [PrimeDAO/prime-deals-dapp#662]
On the deal dashboard page, type and total representatives should be separated with a line and space like the other lines

![image.png](https://images.zenhubusercontent.com/609a98a27efca047604a4836/13e1d21f-301a-4f1e-a375-9caa5bc92de8)

**Comment by v0ort** [comment]
I would disagree in this one. The line is to emphasize certain metrics. It  was not intended to put between al metrics. Also the image is outdated because we need to add deal lead. Example attached
<img width="541" alt="Screenshot 2022-04-15 at 10 40 11" src="https://user-images.githubusercontent.com/90451455/163547949-5df63759-291c-4e08-9c62-f0c105994717.png">

**Comment by renc-curvelabs** [comment]
"Deal Lead" should be "Proposal Lead" and there should be a separate ticket on that.  @IonelLupu @v0ort
